---
title: "Untitled"
runtime: shiny
output: flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(shiny)
knitr::opts_chunk$set(echo = FALSE)
```

## Shiny Presentation {.sidebar}

This R Markdown presentation is made interactive using Shiny. The viewers of the presentation can change the assumptions underlying what's presented and see the results immediately. 

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

## Interactive Plot

### Input

```{r eruptions}
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
)
```

### Output
```{r eruptions-plot}
renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```

## Some Results

### Bullets

- Bullet 1
- Bullet 2
- Bullet 3

### R Output

```{r cars}
summary(cars)
```
